### ISSUE TITLE
Paxedit deletes a space when point is at beginning of a symbol

### ISSUE THREAD

**Issue by tuhdo** [promethial/paxedit#5]
For example:

```elisp
(defun []function-name())
```
`[]` is the cursor. When we execute `paxedit-copy`, it deletes one space backward. If the cursor is on `f` character, a space is deleted and we are in trouble.

**Comment by promethial** [comment]
Nice catch @tuhdo. I was able to replicate the issue and find the root cause. The bug fix is part of the v1.1.5 release. Let me know how it works :-)

**Comment by tuhdo** [comment]
It is fixed. Thanks.
