### ISSUE TITLE
paxedit-previous-symbol should stop when a symbol has an opening paren to the left

### ISSUE THREAD

**Issue by tuhdo** [promethial/paxedit#6]
Currently, paxedit skips over such symbol.

**Comment by promethial** [comment]
Hi tuhdo,

This function was previously an undocumented feature of Paxedit so it might be unclear how it was intended to work. The function is working as designed. I've created a new release v1.1.6 which adds documentation to both `paxedit-previous-symbol` and `paxedit-next-symbol` which explains exactly how these functions are intended to work.

```
Go to the previous symbol regardless of what may seperate the
symbols. Will move to previous symbol regardless if the previous
symbol is at a different depth.

e.g.
 (print (*-!- 123 456))

-> paxedit-previous-symbol

 (print-!- (* 123 456))
```
